# PEDIR LA EDAD A UNA PERSONA, 
#Y MUESTRE UN MENSAJE INFORMANDO SI LA MISMA ES MAYOR DE EDAD O NO


edad = int(input("INGRESE SU EDAD: "))

if (edad >= 18):
	print("ES MAYOR DE EDAD")
else:
	print("ES MENOR DE EDAD")

#ESTRE PRINT YA ESTA POR FUERA DE LA ESTRUCTURA CONDICIONAL (PORQUE NO ESTA CON TABULACION)
print("TERMINAMOS")