# Generated by Django 3.2.19 on 2023-07-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre', models.CharField(max_length=120)),
                ('descrpcion', models.TextField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
